#!/usr/bin/python
#
#  Musense music organization software
#
from mutagen.flac import FLAC
from mutagen.easyid3 import EasyID3
from mutagen.oggvorbis import OggVorbis
import os
import re
import commands
from optparse import OptionParser

def main():

  # Init option parse
  parser = OptionParser(version="1.0")
  (options, args) = parser.parse_args()

  # Get current working dir
  curdir = os.getcwd()

  # Begin main loop
  for i in commands.getoutput("find %s -regextype posix-extended -regex \".*\.(flac|ogg|mp3)\" -not -regex \"\./[A-Z0-9]{1}/.*\"" % curdir).split("\n"):
    artist = None
    fartist = None
    album = None
    title = None
    track = None

    # Match file extension to figure out type of music
    m = re.match(".*\.(mp3|flac|ogg)", i)
    if m:
      if m.group(1) == "mp3":
        audio = EasyID3(i)
        artist = audio.get("artist")[0].encode('ascii', 'ignore')
        fartist = artist[0]
        album = audio.get("album")[0].encode('ascii', 'ignore')
        title = audio.get("title")[0].encode('ascii', 'ignore')
        if audio.has_key("tracknumber"):
          track = re.match("0?([0-9]*)/?.*", audio.get("tracknumber")[0].encode('ascii', 'ignore')).group(1)
          if track == '':
            track = "None"
          new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + track + " - " + title + ".mp3"
        else:
          new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + title + ".mp3"
        if i != new:
          os.renames(i, new)
          print i + " --> " + new
      elif m.group(1) == "flac":
        audio = FLAC(i)
        artist = audio.get("artist")[0].encode('ascii', 'ignore')
        fartist = artist[0]
        album = audio.get("album")[0].encode('ascii', 'ignore')
        title = audio.get("title")[0].encode('ascii', 'ignore')
        if audio.has_key("tracknumber"):
          track = re.match("0?([0-9]*)/?.*", audio.get("tracknumber")[0].encode('ascii', 'ignore')).group(1)
          if track == '':
            track = "None"
          new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + track + " - " + title + ".flac"
        else:
          new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + title + ".flac"
        if i != new:
          os.renames(i, new)
          print i + " --> " + new
      elif m.group(1) == "ogg":
        audio = OggVorbis(i)
        artist = audio.get("artist")[0].encode('ascii', 'ignore')
        fartist = artist[0]
        album = audio.get("album")[0].encode('ascii', 'ignore')
        title = audio.get("title")[0].encode('ascii', 'ignore')
        if audio.has_key("tracknumber"):
          track = re.match("0?([0-9]*)/?.*", audio.get("tracknumber")[0].encode('ascii', 'ignore')).group(1)
          if track == '':
            track = "None"
          new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + track + " - " + title + ".ogg"
        else:
          new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + title + ".ogg"
        if i != new:
          os.renames(i, new)
          print i + " --> " + new
      else:
        print "Uhhh...... What? Not music?"

if __name__ == "__main__":
  main()
