#!/usr/bin/python
#
#  Musense music organization software
#
#  Copyright (C) 2010 Lucas Cycon
#
#  Musense is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Musense is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Musense.  If not, see <http://www.gnu.org/licenses/>.
#
from mutagen.flac import FLAC
from mutagen.easyid3 import EasyID3
from mutagen.oggvorbis import OggVorbis
from mutagen.mp4 import MP4
import os
import re
import commands
from optparse import OptionParser

def main():

  # Init option parse
  parser = OptionParser(version="1.0.1")
  (options, args) = parser.parse_args()

  # Get current working dir
  curdir = os.getcwd()

  # Begin main loop
  for i in commands.getoutput("find %s -regextype posix-extended -regex \".*\.(flac|ogg|mp3|mp4|m4a)\" -not -regex \"\./[A-Z0-9]{1}/.*\"" % curdir).split("\n"):
    artist = None
    fartist = None
    album = None
    title = None
    track = None
    filetype = None

    # Match file extension to figure out type of music
    m = re.match(".*\.(mp3|flac|ogg|mp4|m4a)", i)
    if m:
      filetype = m.group(1)
      if filetype == "mp3":
        audio = EasyID3(i)
      elif filetype == "flac":
        audio = FLAC(i)
      elif filetype == "ogg":
        audio = OggVorbis(i)
      elif filetype == "mp4" || filetype = "m4a":
        audio = MP4(i)
      else:
        print "Unknown. This should never happen."
    rename(i, audio, curdir, filetype)

def rename(i, audio, curdir, ext):
  artist = audio.get("artist")[0].encode('ascii', 'ignore')
  fartist = artist[0]
  album = audio.get("album")[0].encode('ascii', 'ignore')
  title = audio.get("title")[0].encode('ascii', 'ignore')
  if audio.has_key("tracknumber"):
    track = re.match("0?([0-9]*)/?.*", audio.get("tracknumber")[0].encode('ascii', 'ignore')).group(1)
    if track == '':
      track = "None"
    new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + track + " - " + title + "." + ext
  else:
    new = curdir + "/" + fartist + "/" + artist + "/" + album + "/" + title + "." + ext
  if i != new:
      os.renames(i, new)
      print i + " --> " + new

if __name__ == "__main__":
  main()
